### ISSUE TITLE
Failed plugin build in UE4.20

### ISSUE THREAD

**Issue by peachthiefmedia** [code-iai/ROSIntegration#48]
The recent update to SensorMsgsImageConverter (in Private/Conversion/Messages/sensor_msgs) seems to be blocking the plugin from building now, at least in UE 4.20 error in build log is

> \Private\Conversion/Messages/sensor_msgs/SensorMsgsImageConverter.h(37): error C2039: 'data': is not a member of 'ROSMessages::sensor_msgs::Image'
> \Public\sensor_msgs/Image.h(8): note: see declaration of 'ROSMessages::sensor_msgs::Image'

If you comment out line 37 in SensorMsgsImageConverter it builds fine; don't think it is due to building on 4.20 looking at it quickly.
Building with VS2017 on W10 with UE 4.20.3

**Comment by Hemofektik** [comment]
There is already a PR #47 to fix this issue.

**Comment by peachthiefmedia** [comment]
Sorry I missed looking for it in a pull, I can close this or leave it here for people trying to build in 4.20 until the request is accepted?

**Comment by Hemofektik** [comment]
No problem, as you already found out it should run fine with 4.20 with the fix. Feel free to leave the issue open until the PR is merged.

**Comment by Sanic** [comment]
PR is merged -> Closing this issue
